require("myfuckingshit.plugin")
require("myfuckingshit.remap")
require("myfuckingshit.set")
require("myfuckingshit.run_code")
require("myfuckingshit.exit_current_dir")
require("myfuckingshit.autocmd")
